# Site settings
title: Ken Sin
email: anythingken@gmail.com
description: "wut up doe"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: nisnek
github_username:  ksin

# Build settings
markdown: kramdown
permalink: pretty
